// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Infrastructure.Persistence.Data;

#nullable disable

namespace TechStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121112453_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechStore.Domain.Entities.CategoryDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescription = "Mobile phones and smart devices",
                            CategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescription = "Portable computers and notebooks",
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            CategoryDescription = "Touch-based portable devices",
                            CategoryName = "Tablets"
                        },
                        new
                        {
                            Id = 4,
                            CategoryDescription = "Wearable smart devices",
                            CategoryName = "Smart Watches"
                        },
                        new
                        {
                            Id = 5,
                            CategoryDescription = "Audio devices and earphones",
                            CategoryName = "Headphones"
                        },
                        new
                        {
                            Id = 6,
                            CategoryDescription = "Devices for gaming and entertainment",
                            CategoryName = "Gaming Consoles"
                        },
                        new
                        {
                            Id = 7,
                            CategoryDescription = "Tech accessories and peripherals",
                            CategoryName = "Accessories"
                        });
                });

            modelBuilder.Entity("TechStore.Domain.Entities.ProductDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 1199m,
                            ProductDescription = "Apple flagship smartphone",
                            ProductName = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "Apple previous generation phone",
                            ProductName = "iPhone 14"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 1099m,
                            ProductDescription = "Samsung top-tier phone",
                            ProductName = "Samsung Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "High-end Samsung smartphone",
                            ProductName = "Samsung Galaxy S23"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 999m,
                            ProductDescription = "Google AI-powered flagship",
                            ProductName = "Google Pixel 8 Pro"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Inventory = 28,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Affordable flagship experience",
                            ProductName = "Google Pixel 7"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "Xiaomi premium phone with Leica camera",
                            ProductName = "Xiaomi 14 Pro"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 299m,
                            ProductDescription = "Best mid-range Xiaomi device",
                            ProductName = "Xiaomi Redmi Note 12 Pro"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 699m,
                            ProductDescription = "High-performance flagship killer",
                            ProductName = "OnePlus 12"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 329m,
                            ProductDescription = "Mid-range OnePlus smartphone",
                            ProductName = "OnePlus Nord CE 3"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 899m,
                            ProductDescription = "Premium camera-focused smartphone",
                            ProductName = "Huawei P60 Pro"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 399m,
                            ProductDescription = "Stylish mid-range smartphone",
                            ProductName = "Huawei Nova 11"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 1299m,
                            ProductDescription = "Sony flagship with pro camera features",
                            ProductName = "Sony Xperia 1 V"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Inventory = 14,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "Compact premium smartphone",
                            ProductName = "Sony Xperia 5 V"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Eco-friendly smartphone",
                            ProductName = "Nokia X30"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 899m,
                            ProductDescription = "Motorola flagship smartphone",
                            ProductName = "Motorola Edge 40 Pro"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Inventory = 45,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Affordable phone with long battery",
                            ProductName = "Motorola Moto G Power 2023"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 999m,
                            ProductDescription = "Gaming smartphone beast",
                            ProductName = "Asus ROG Phone 7"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Unique transparent design phone",
                            ProductName = "Nothing Phone 2"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Inventory = 26,
                            IsDeleted = false,
                            Price = 549m,
                            ProductDescription = "Affordable flagship performance",
                            ProductName = "Realme GT 5 Pro"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 1299m,
                            ProductDescription = "Lightweight Apple laptop",
                            ProductName = "MacBook Air M3"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Inventory = 8,
                            IsDeleted = false,
                            Price = 3499m,
                            ProductDescription = "Apple high-performance laptop",
                            ProductName = "MacBook Pro 16 M3 Max"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 2199m,
                            ProductDescription = "Apple portable powerhouse",
                            ProductName = "MacBook Pro 14 M3"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 1799m,
                            ProductDescription = "Dell premium ultrabook",
                            ProductName = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Affordable laptop for students",
                            ProductName = "Dell Inspiron 14"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Inventory = 11,
                            IsDeleted = false,
                            Price = 1599m,
                            ProductDescription = "Premium 2-in-1 ultrabook",
                            ProductName = "HP Spectre x360"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Budget-friendly laptop",
                            ProductName = "HP Pavilion 15"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Inventory = 14,
                            IsDeleted = false,
                            Price = 1699m,
                            ProductDescription = "Business ultrabook",
                            ProductName = "Lenovo ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Inventory = 9,
                            IsDeleted = false,
                            Price = 2299m,
                            ProductDescription = "High-end gaming laptop",
                            ProductName = "Lenovo Legion 7"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 1599m,
                            ProductDescription = "Compact gaming laptop",
                            ProductName = "ASUS ROG Zephyrus G14"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 699m,
                            ProductDescription = "Affordable ultrabook",
                            ProductName = "ASUS VivoBook S15"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 649m,
                            ProductDescription = "Lightweight student laptop",
                            ProductName = "Acer Swift 3"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 1399m,
                            ProductDescription = "Mid-range gaming laptop",
                            ProductName = "Acer Predator Helios 300"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 1999m,
                            ProductDescription = "Professional creator laptop",
                            ProductName = "MSI Stealth 16 Studio"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Inventory = 8,
                            IsDeleted = false,
                            Price = 2499m,
                            ProductDescription = "Premium gaming laptop",
                            ProductName = "Razer Blade 15"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Inventory = 14,
                            IsDeleted = false,
                            Price = 1299m,
                            ProductDescription = "Apple flagship tablet",
                            ProductName = "iPad Pro 12.9 M2"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Powerful lightweight tablet",
                            ProductName = "iPad Air M1"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 449m,
                            ProductDescription = "Affordable Apple tablet",
                            ProductName = "iPad 10th Gen"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 899m,
                            ProductDescription = "Premium Android tablet",
                            ProductName = "Samsung Galaxy Tab S9"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Budget Android tablet",
                            ProductName = "Samsung Tab A8"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 399m,
                            ProductDescription = "Affordable power tablet",
                            ProductName = "Xiaomi Pad 6"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 699m,
                            ProductDescription = "High-end productivity tablet",
                            ProductName = "Lenovo Tab P12 Pro"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 149m,
                            ProductDescription = "Budget media tablet",
                            ProductName = "Amazon Fire HD 10"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Premium Huawei tablet",
                            ProductName = "Huawei MatePad 11"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Inventory = 32,
                            IsDeleted = false,
                            Price = 229m,
                            ProductDescription = "Affordable entertainment tablet",
                            ProductName = "Realme Pad 2"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Inventory = 28,
                            IsDeleted = false,
                            Price = 399m,
                            ProductDescription = "Top smartwatch from Apple",
                            ProductName = "Apple Watch Series 9"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "Rugged smartwatch for professionals",
                            ProductName = "Apple Watch Ultra 2"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Inventory = 26,
                            IsDeleted = false,
                            Price = 349m,
                            ProductDescription = "Samsung premium smartwatch",
                            ProductName = "Samsung Galaxy Watch 6"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 399m,
                            ProductDescription = "Classic design smartwatch",
                            ProductName = "Samsung Galaxy Watch 6 Classic"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 249m,
                            ProductDescription = "Long-lasting smartwatch",
                            ProductName = "Huawei Watch GT 4"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Stylish Xiaomi smartwatch",
                            ProductName = "Xiaomi Watch S1 Pro"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 4,
                            Inventory = 45,
                            IsDeleted = false,
                            Price = 179m,
                            ProductDescription = "Fitness and health smartwatch",
                            ProductName = "Amazfit GTR 4"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 229m,
                            ProductDescription = "Fitness-focused smartwatch",
                            ProductName = "Fitbit Sense 2"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 4,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 349m,
                            ProductDescription = "Running-focused watch",
                            ProductName = "Garmin Forerunner 255"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 799m,
                            ProductDescription = "Premium outdoor GPS watch",
                            ProductName = "Garmin Fenix 7"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            Inventory = 50,
                            IsDeleted = false,
                            Price = 249m,
                            ProductDescription = "ANC wireless earbuds",
                            ProductName = "AirPods Pro 2"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 549m,
                            ProductDescription = "Premium over-ear headphones",
                            ProductName = "AirPods Max"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 349m,
                            ProductDescription = "Top ANC headphones",
                            ProductName = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 299m,
                            ProductDescription = "Premium earbuds",
                            ProductName = "Sony WF-1000XM5"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Samsung ANC earbuds",
                            ProductName = "Samsung Galaxy Buds 2 Pro"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 5,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 149m,
                            ProductDescription = "Wireless over-ear",
                            ProductName = "JBL Live 660NC"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            Inventory = 45,
                            IsDeleted = false,
                            Price = 79m,
                            ProductDescription = "Budget ANC earbuds",
                            ProductName = "JBL Tune 230NC"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 5,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 329m,
                            ProductDescription = "Premium ANC headset",
                            ProductName = "Bose QuietComfort 45"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 299m,
                            ProductDescription = "High-end ANC earbuds",
                            ProductName = "Bose QuietComfort Earbuds II"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 5,
                            Inventory = 50,
                            IsDeleted = false,
                            Price = 129m,
                            ProductDescription = "Affordable ANC earbuds",
                            ProductName = "Anker Soundcore Liberty 4"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 5,
                            Inventory = 16,
                            IsDeleted = false,
                            Price = 349m,
                            ProductDescription = "Audiophile-grade ANC headset",
                            ProductName = "Sennheiser Momentum 4"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 5,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 249m,
                            ProductDescription = "Fashionable wireless headphones",
                            ProductName = "Beats Studio3 Wireless"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 5,
                            Inventory = 28,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Sports earbuds with ANC",
                            ProductName = "Beats Fit Pro"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 169m,
                            ProductDescription = "Gaming ANC earbuds",
                            ProductName = "Razer Hammerhead Pro"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 5,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 129m,
                            ProductDescription = "Professional gaming headset",
                            ProductName = "Logitech G Pro X"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Sony next-gen console",
                            ProductName = "PlayStation 5"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 399m,
                            ProductDescription = "Digital-only PS5",
                            ProductName = "PlayStation 5 Digital"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 6,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Powerful Microsoft console",
                            ProductName = "Xbox Series X"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 6,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 299m,
                            ProductDescription = "Affordable Xbox console",
                            ProductName = "Xbox Series S"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 349m,
                            ProductDescription = "Hybrid gaming console",
                            ProductName = "Nintendo Switch OLED"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 6,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Portable-only Nintendo console",
                            ProductName = "Nintendo Switch Lite"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 6,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Valve portable gaming PC",
                            ProductName = "Steam Deck OLED"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 599m,
                            ProductDescription = "Portable Windows gaming device",
                            ProductName = "ASUS ROG Ally"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 6,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 549m,
                            ProductDescription = "Sony VR headset",
                            ProductName = "PlayStation VR2"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 6,
                            Inventory = 16,
                            IsDeleted = false,
                            Price = 499m,
                            ProductDescription = "Standalone VR headset",
                            ProductName = "Meta Quest 3"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 7,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 99m,
                            ProductDescription = "Premium wireless mouse",
                            ProductName = "Logitech MX Master 3S"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 7,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 119m,
                            ProductDescription = "Professional wireless keyboard",
                            ProductName = "Logitech MX Keys"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            Inventory = 32,
                            IsDeleted = false,
                            Price = 69m,
                            ProductDescription = "High-performance gaming mouse",
                            ProductName = "Razer DeathAdder V3"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 7,
                            Inventory = 12,
                            IsDeleted = false,
                            Price = 229m,
                            ProductDescription = "Premium mechanical keyboard",
                            ProductName = "Corsair K100 RGB"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 7,
                            Inventory = 18,
                            IsDeleted = false,
                            Price = 199m,
                            ProductDescription = "Gaming mechanical keyboard",
                            ProductName = "SteelSeries Apex Pro"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            Inventory = 28,
                            IsDeleted = false,
                            Price = 79m,
                            ProductDescription = "Professional webcam",
                            ProductName = "Logitech C920 HD Webcam"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 7,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 149m,
                            ProductDescription = "Creator control panel",
                            ProductName = "Elgato Stream Deck"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 7,
                            Inventory = 50,
                            IsDeleted = false,
                            Price = 49m,
                            ProductDescription = "Portable power bank",
                            ProductName = "Anker PowerCore 20k"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 7,
                            Inventory = 35,
                            IsDeleted = false,
                            Price = 59m,
                            ProductDescription = "Laptop hub expansion",
                            ProductName = "Anker USB-C Hub 7-in-1"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 7,
                            Inventory = 55,
                            IsDeleted = false,
                            Price = 29m,
                            ProductDescription = "Fast USB-C charger",
                            ProductName = "Samsung 25W Super Fast Charger"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 7,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 59m,
                            ProductDescription = "Fast MacBook charger",
                            ProductName = "Apple USB-C 70W Charger"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 7,
                            Inventory = 100,
                            IsDeleted = false,
                            Price = 19m,
                            ProductDescription = "Phone car holder",
                            ProductName = "Baseus Magnetic Car Mount"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 7,
                            Inventory = 200,
                            IsDeleted = false,
                            Price = 12m,
                            ProductDescription = "High-speed charging cable",
                            ProductName = "UGREEN USB-C Cable 100W"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 7,
                            Inventory = 22,
                            IsDeleted = false,
                            Price = 129m,
                            ProductDescription = "Portable SSD storage",
                            ProductName = "Sandisk Extreme 1TB SSD"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 7,
                            Inventory = 15,
                            IsDeleted = false,
                            Price = 249m,
                            ProductDescription = "Ultra-fast NVMe SSD",
                            ProductName = "WD Black SN850 2TB"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 7,
                            Inventory = 25,
                            IsDeleted = false,
                            Price = 99m,
                            ProductDescription = "Gaming headset",
                            ProductName = "HyperX Cloud II"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 7,
                            Inventory = 40,
                            IsDeleted = false,
                            Price = 49m,
                            ProductDescription = "Gaming mouse",
                            ProductName = "Logitech G502 Hero"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 7,
                            Inventory = 30,
                            IsDeleted = false,
                            Price = 49m,
                            ProductDescription = "RGB gaming pad",
                            ProductName = "Razer Firefly RGB Mousepad"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 7,
                            Inventory = 20,
                            IsDeleted = false,
                            Price = 159m,
                            ProductDescription = "Rugged portable SSD",
                            ProductName = "Samsung T7 Shield SSD"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 7,
                            Inventory = 10,
                            IsDeleted = false,
                            Price = 249m,
                            ProductDescription = "Premium 4K player",
                            ProductName = "Sony 4K Blu-ray Player"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechStore.Domain.Entities.ProductDomain", b =>
                {
                    b.HasOne("TechStore.Domain.Entities.CategoryDomain", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechStore.Domain.Entities.CategoryDomain", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
